apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: cnViYmVyCg==
  password: ZHVja3kK
---
apiVersion: v1
kind: Pod
metadata:
  name: mysecret-fs-pod
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
      - name: "secrets"
        mountPath: "/etc/mysecrets"
        readOnly: true
  volumes:
    - name: "secrets"
      secret:
        secretName: "mysecret"
  restartPolicy: Never