apiVersion: v1
kind: ReplicationController
metadata:
  name: deis-monitor-grafana
  namespace: deis
  labels:
    heritage: deis
spec:
  replicas: 1
  selector:
    app: deis-monitor-grafana
  template:
    metadata:
      labels:
        app: deis-monitor-grafana
    spec:
      containers:
      - name: deis-monitor-grafana
        image: quay.io/deis/grafana:canary
        imagePullPolicy: Always
        env:
        - name: "INFLUXDB_URLS"
          value: http://$(DEIS_MONITOR_INFLUXAPI_SERVICE_HOST):$(DEIS_MONITOR_INFLUXAPI_SERVICE_PORT_TRANSPORT)
        - name: "BIND_PORT"
          value: "3500"
        ports:
        - containerPort: 3500
          name: ui
