apiVersion: v1
kind: Secret
metadata:
  name: objectstorage-keyfile
  namespace: deis
  labels:
    heritage: deis
  annotations:
    deis.io/objectstorage: "{{.storage}}"
type: Opaque
data: {{ if eq .storage "minio" }}
  access-key-id: OFRaUlkySlJXTVBUNlVNWFI2STUK
  access-secret-key: Z2JzdHJPdm90TU1jZzJzTWZHVWhBNWE2RXQvRUk1QUx0SUhzb2JZawo={{ else if eq .storage "gcs" }}
  key.json: {{ b64enc .gcs.key_json }}
  bucket: {{ b64enc .gcs.bucket }}{{ else if eq .storage "azure" }}
  accountname: {{ b64enc .azure.accountname }}
  accountkey: {{ b64enc .azure.accountkey }}
  container: {{ b64enc .azure.container }}{{ else if eq .storage "s3" }}
  accesskey: {{ b64enc .s3.accesskey }}
  secretkey: {{ b64enc .s3.secretkey }}
  region: {{ b64enc .s3.region }}
  bucket: {{ b64enc .s3.bucket }}
  database-bucket: {{ b64enc .s3.database_bucket }}{{ end }}
