language: ruby
sudo: false
cache: bundler
bundler_args: "--without development"

before_install:
  - "gem update --system"
  - "gem install bundler"

rvm:
- 2.0.0
- 2.1
- 2.2
- 2.3.6
- 2.4.3
- 2.5.0
- ruby-head
- jruby-9.1.13.0

matrix:
  allow_failures:
    - rvm: ruby-head

notifications:
  slack:
    secure: Ld0tGBmwLG/ADOlLjO6ILq98+u/iq5qkuxAwN1E0SBOooALZZEJSc74jEMpgpnb22tk8QimUmLiCTE+8tWKaGiXTrvK6uvvfP6iiL9850NezHCxA3YMuWPnQQtJpTJ4135MMO8gJXu9vcswb9vW9N3v/A7VJdHbVZyT0vIMGas0=
