coverage:
  status:
    project:
      default:
        # Fail the status if coverage drops by >= 2%
        threshold: 2
    patch:
      default:
        # Fail the status if coverage drops by >= 2%
        threshold: 2

comment:
  layout: diff
  require_changes: yes
