apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: #helm_name#-steward
  namespace: steward
  labels:
    app: #helm_name#-steward
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: #helm_name#-steward
    spec:
      containers:
          - name: #helm_name#-steward
          image: #steward_image#
          imagePullPolicy: Always
          env:
          - name: BROKER_NAME
            value: #helm_name#
          - name: STEWARD_MODE
            value: helm
          - WATCH_NAMESPACES
            value: default
          - name: LOG_LEVEL
            value: trace
          - name: HELM_TILLER_IP
            value: "#helm_tiller_ip#"
          - name: HELM_TILLER_PORT
            value: "#helm_tiller_port#"
          - name: HELM_CHART_URL
            value: "#helm_chart_url"
          - name: HELM_CHART_INSTALL_NAMESPACE
            value: "#helm_chart_install_namespace#"
          - name: HELM_PROVISION_BEHAVIOR
            value: "#helm_provision_behavior#"
          - name: HELM_SERVICE_ID
            value: "#helm_service_id#"
          - name: HELM_SERVICE_NAME
            value: "#helm_service_name#"
          - name: HELM_SERVICE_DESCRIPTION
            value: "#helm_service_description#"
          - name: HELM_PLAN_ID
            value: "#helm_plan_id#"
          - name: HELM_PLAN_NAME
            value: "#helm_plan_name#"
          - name: HELM_PLAN_DESCRIPTION
            value: "#helm_plan_description#"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            failureThreshold: 1
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: #helm-steward
  namespace: steward
  labels:
    app: #helm-steward
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: #helm-steward
