apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: #cmd_broker_name#-steward
  namespace: steward
  labels:
    app: #cmd_broker_name#-steward
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: #cmd_broker_name#-steward
    spec:
      containers:
      - name: #cmd_broker_name#-steward
        image: #steward_image#
        imagePullPolicy: Always
        env:
        - name: BROKER_NAME
          value: #cmd_broker_name#
        - name: LOG_LEVEL
          value: trace
        - name: STEWARD_MODE
          value: cmd
        - name: WATCH_NAMESPACES
          value: default
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CMD_IMAGE
          value: #cmd_broker_image#
        - name: CMD_CONFIG_MAP
          value: #cmd_broker_config_map#
        - name: CMD_SECRET
          value: #cmd_broker_secret#
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: #cmd_broker_name#-steward
  namespace: steward
  labels:
    app: #cmd_broker_name#-steward
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: #cmd_broker_name#-steward
