apiVersion: v1
kind: Service
metadata:
  name: tiller
  namespace: kube-system
spec:
  type: ClusterIP
  selector:
    app: helm
    name: tiller
  ports:
    - name: tiller
      port: 44134
      targetPort: tiller
