language: generic
branches:
  only:
  - master
cache:
  directories:
  - vendor
sudo: required
services:
- docker
install:
- make bootstrap
script:
- make build docker-build
deploy:
- provider: script
  script: _scripts/deploy.sh
  on:
    branch: master
notifications:
  webhooks:
    urls:
      - secure: "Q36F2HV54wekMrOkEaqQjMZHBGrFw6AeQXTrFqy9R9zr6es7lDiqLc9yd/dcWq23wAe4v4Hyk9lYvXRbkXdpqE68JR1rWTMl7Jw2BxtJChBuOGQhkciiU67/qP/4fT7z52RftiMds+pGVX/h9jZlau4WMIEeiPMMzsPpmdvsjfWu8GnNdHIx/qTGjPLdQRNLV9CM4mzENEwIZU5d08l4nCsfXGPVddKvrJjVAtsVdCLKed6qjm/aqKhDMoo20a8sgFX95c3DHEH6QWZj1Nzl9AflSmDCgy8Iv+MDfddQiFq9BsZ0cVN5ZrYyxk9i5jFtO5ObICOi6ZB1H4YM0fSLmyvFFO/ftETGtDPx+Z9aXLmr/7oMAL6pY87hMMaitjScDVQr4oHOZlUbovTfObq0Nv0LATHRcPMFLiefqh8KGksXJdVDd9fDdiFbFgX+u7NpzWgw0PQUerpFV3V34ep7JeKW6by/bq9aIuXl/misximm8lr8mJWcQ/HexCIObrrY9n2Ou1Zj76hwgCSXwtUye+UyvbtiAE5zPKHJI45HTZoAg5HIQ+MpDGLGPwDok81az1aBFqGkCed88QmvxaimG2CpgeRC3BtbXfedUvvBXSK+2gCuzuoM/RlT1u047NiyHO1idb7vYIdgdWzd6H41sHpcunarxuTfSFH5Ov0iSsA="
    on_success: always
    on_failure: never
    on_start: never
