---
kind: Service
apiVersion: v1
metadata:
  name: phippy
  labels:
    app: phippy
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3333
    protocol: TCP
    name: phippy
  selector:
    app: phippy
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: phippy
  labels:
    draft: draft-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: phippy
    spec:
      automountServiceAccountToken: false
      containers:
      - name: phippy
        image: "jhansen/phippy:v0.0.1"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3333