#helm:generate helm tpl -d $HELM_GENERATE_DIR/tpl/generate_params.toml -o $HELM_GENERATE_DIR/manifests/deis-tests-pod.yaml $HELM_GENERATE_DIR/tpl/deis-tests-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: workflow-beta1-e2e
  namespace: deis
  labels:
    heritage: deis
spec:
  restartPolicy: Never
  containers:
  - name: deis-e2e
    image: quay.io/{{.e2e.org}}/deis-e2e:{{.e2e.dockerTag}}
    imagePullPolicy: {{.e2e.pullPolicy}}
    command: ["/bin/tests.test"]
    args: ["-test.v", "-test.timeout=60m", "-ginkgo.v", "-ginkgo.slowSpecThreshold=120"]
    env:
      - name: JUNIT
        value: "true"
    volumeMounts:
    - name: artifact-volume
      mountPath: /root
  - name: artifacts
    image: busybox
    imagePullPolicy: Always
    command: ["tail", "-f", "/dev/null"]
    volumeMounts:
    - name: artifact-volume
      mountPath: /root
  volumes:
  - name: artifact-volume
    emptyDir: {}
