apiVersion: v1
kind: Pod
metadata:
  name: invalid-pod
  namespace: limits
spec:
  containers:
  - name: kubernetes-serve-hostname
    image: gcr.io/google_containers/serve_hostname
    resources:
      limits:
        cpu: "2"
        memory: 100Mi