apiVersion: v1
kind: Pod
metadata:
  name: redis-django
  labels:
    app: web
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379
    - name: croc-hunter
      image: quay.io/lachie83/croc-hunter:v1
      ports:
        - containerPort: 8080